apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260510-210220-wnf7f1t0lfsy-service
spec:
  selector:
    app: enterprise-system-20260510-210220-wnf7f1t0lfsy
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
